# SITE CONFIGURATION
title: yucheon # your site title
author: yucheon # You :P
description: > # Meta description of Homepage
  차곡차곡 쌓아가는 개발 이야기
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.yucheon.io" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: yucheon6000
  links:
    # - https://twitter.com/BenBalter
    # - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/6000
    # - https://plus.google.com/+BenBalter
    - https://github.com/yucheon6000
    # - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  차곡차곡 쌓아가는 개발 이야기

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: 6000@yucheon.io # email for form submission

# twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  yucheon6000 # replace with your_github_username or comment to remove link from footer
instagram_username: park_6000 # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: yucheon6000 # to enable comments replace with your_disqus_shortname

google_tag_manager: G-90T6R3TF7W # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /posts/:year/:month/:day/:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

futrue: true
